kind: Service
apiVersion: v1
metadata:
  name: ntm-db-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
  type: NodePort
  selector:
    app: ntm-db-statefulset
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: ntm-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ntm-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
kind: StatefulSet
apiVersion: apps/v1beta2
metadata:
  name: ntm-db-statefulset
  labels:
    app: ntm-db-statefulset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ntm-db-statefulset
  serviceName: ntm-db-statefulset
  template:
    metadata:
      labels:
        app: ntm-db-statefulset
    spec:
      volumes:
        - name: ntm-db-storage
          persistentVolumeClaim:
            claimName: ntm-pv-claim
      containers:
      - name: ntm-db
        image: postgres:9.6.9
        ports:
          - containerPort: 5432
            name: postgres
        volumeMounts:
        - name: ntm-db-storage
          mountPath: /usr/share/postgres
        env:
          - name : POSTGRES_DB
            value: ncp_core_db
          - name : POSTGRES_USER
            value: itm_core
          - name : POSTGRES_PASSWORD
            value: ~@WSX3edc
          - name : POSTGRES_INITDB_ARGS
            value: --encoding=UTF-8
          - name : TZ
            value: Asia/Seoul
#      environment:
#        - POSTGRES_DB=ncp_core_db
#        - POSTGRES_USER=itm_core
#        - POSTGRES_PASSWORD=~@WSX3edc
#        - POSTGRES_INITDB_ARGS=--encoding=UTF-8
#        - TZ=Asia/Seoul
#      healthcheck:
#        test: "pg_isready -h localhost -p 5432 -q -U itm_core"
#        interval: 3s
#        timeout: 1s
#        retries: 10
#  volumeClaimTemplates:
#  - metadata:
#      name: postgres-storage
#    spec:
#      accessModes: [ "ReadWriteOnce" ]
#      storageClassName: ntm-db-storage
#      resources:
#        requests:
#          storage: 1Gi
