kind: StatefulSet
apiVersion: apps/v1beta2
metadata:
  name: ntm-db
  labels:
    app: ntm-db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ntm-db
  serviceName: "ntmDB"
  template:
    metadata:
      labels:
        app: ntm-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: ntm-db
        image: postgres:9.6.9
        ports:
          - containerPort: 5432
            name: mysql
        volumeMounts:
        - name: db
          mountPath: /usr/share/postgres
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: examplepassword
      environment:
        - POSTGRES_DB=ncp_core_db
        - POSTGRES_USER=itm_core
        - POSTGRES_PASSWORD=~@WSX3edc
        - POSTGRES_INITDB_ARGS=--encoding=UTF-8
        - TZ=Asia/Seoul
      healthcheck:
        test: "pg_isready -h localhost -p 5432 -q -U itm_core"
        interval: 3s
        timeout: 1s
        retries: 10
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ntm-db-storage-class"
      resources:
        requests:
          storage: 1Gi
